language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - "pip install codecov"
  - "pip install -r requirements.txt"
script:
  - "export PYTHONPATH=${PWD}:${PYTHONPATH}"
  - "nosetests --with-coverage --cover-package=bidsmanager -w ./test test"
  - "codecov"
